import { CatalogItem } from '../types/index.js';

export const INITIAL_CATALOGS: CatalogItem[] = [
  // Alergias comunes
  { id: 'al-01', category: 'alergia', name: 'Penicilinas y derivados', code: 'ALG-001', frequency: 100 },
  { id: 'al-02', category: 'alergia', name: 'Amoxicilina / Ampicilina', code: 'ALG-002', frequency: 95 },
  { id: 'al-03', category: 'alergia', name: 'Cefalosporinas', code: 'ALG-003', frequency: 70 },
  { id: 'al-04', category: 'alergia', name: 'Sulfamidas (Trimetoprim/Sulfametoxazol)', code: 'ALG-004', frequency: 80 },
  { id: 'al-05', category: 'alergia', name: 'Aspirina (Acido acetilsalicilico)', code: 'ALG-005', frequency: 85 },
  { id: 'al-06', category: 'alergia', name: 'Ibuprofeno y otros AINEs', code: 'ALG-006', frequency: 90 },
  { id: 'al-07', category: 'alergia', name: 'Dipirona / Metamizol', code: 'ALG-007', frequency: 75 },
  { id: 'al-08', category: 'alergia', name: 'Medios de contraste radiologicos yodados', code: 'ALG-008', frequency: 65 },
  { id: 'al-09', category: 'alergia', name: 'Latex', code: 'ALG-009', frequency: 60 },
  { id: 'al-10', category: 'alergia', name: 'Morfina y derivados opioides', code: 'ALG-010', frequency: 55 },
  { id: 'al-11', category: 'alergia', name: 'Tramadol', code: 'ALG-011', frequency: 50 },
  { id: 'al-12', category: 'alergia', name: 'Quinolonas (Ciprofloxacino, Levofloxacino)', code: 'ALG-012', frequency: 45 },

  // Medicamentos habituales
  { id: 'med-01', category: 'medicamento', name: 'Acetaminofen / Paracetamol 500mg-1g', code: 'MED-001', frequency: 100 },
  { id: 'med-02', category: 'medicamento', name: 'Ibuprofeno 400mg-600mg', code: 'MED-002', frequency: 90 },
  { id: 'med-03', category: 'medicamento', name: 'Losartan 50mg-100mg cada 12-24h', code: 'MED-003', frequency: 95 },
  { id: 'med-04', category: 'medicamento', name: 'Enalapril 10mg-20mg cada 12-24h', code: 'MED-004', frequency: 85 },
  { id: 'med-05', category: 'medicamento', name: 'Amlodipino 5mg-10mg cada 24h', code: 'MED-005', frequency: 88 },
  { id: 'med-06', category: 'medicamento', name: 'Metformina 850mg cada 12h', code: 'MED-006', frequency: 92 },
  { id: 'med-07', category: 'medicamento', name: 'Omeprazol 20mg-40mg al dia', code: 'MED-007', frequency: 94 },
  { id: 'med-08', category: 'medicamento', name: 'Pantoprazol 40mg IV/oral cada 24h', code: 'MED-008', frequency: 80 },
  { id: 'med-09', category: 'medicamento', name: 'Atorvastatina 20mg-40mg cada 24h', code: 'MED-009', frequency: 91 },
  { id: 'med-10', category: 'medicamento', name: 'Levotiroxina sodica 50mcg-100mcg ayunas', code: 'MED-010', frequency: 86 },
  { id: 'med-11', category: 'medicamento', name: 'Salbutamol inhalador 100mcg', code: 'MED-011', frequency: 82 },
  { id: 'med-12', category: 'medicamento', name: 'Furosemida 20mg-40mg oral/IV', code: 'MED-012', frequency: 78 },
  { id: 'med-13', category: 'medicamento', name: 'Hidroclorotiazida 25mg cada 24h', code: 'MED-013', frequency: 75 },
  { id: 'med-14', category: 'medicamento', name: 'Ceftriaxona 1g-2g IV cada 24h', code: 'MED-014', frequency: 85 },
  { id: 'med-15', category: 'medicamento', name: 'Ampicilina / Sulbactam 1.5g-3g IV cada 6h', code: 'MED-015', frequency: 80 },
  { id: 'med-16', category: 'medicamento', name: 'Enoxaparina 40mg-60mg SC cada 24h', code: 'MED-016', frequency: 84 },
  { id: 'med-17', category: 'medicamento', name: 'Insulina Glargina segun esquema', code: 'MED-017', frequency: 72 },
  { id: 'med-18', category: 'medicamento', name: 'Clopidogrel 75mg cada 24h', code: 'MED-018', frequency: 70 },

  // Diagnósticos (CIE-10 / Formato hospitalario)
  { id: 'dx-01', category: 'diagnostico', code: 'I10', name: 'I10 - Hipertension arterial esencial (primaria)', frequency: 99 },
  { id: 'dx-02', category: 'diagnostico', code: 'E11.9', name: 'E11.9 - Diabetes mellitus tipo 2 sin complicaciones', frequency: 95 },
  { id: 'dx-03', category: 'diagnostico', code: 'J18.9', name: 'J18.9 - Neumonia bacteriana no especificada', frequency: 90 },
  { id: 'dx-04', category: 'diagnostico', code: 'J44.1', name: 'J44.1 - Enfermedad pulmonar obstructiva cronica (EPOC) con exacerbacion aguda', frequency: 88 },
  { id: 'dx-05', category: 'diagnostico', code: 'I50.9', name: 'I50.9 - Insuficiencia cardiaca descompensada', frequency: 86 },
  { id: 'dx-06', category: 'diagnostico', code: 'N17.9', name: 'N17.9 - Insuficiencia renal aguda no especificada', frequency: 82 },
  { id: 'dx-07', category: 'diagnostico', code: 'N18.5', name: 'N18.5 - Enfermedad renal cronica estadio 5 / terminal', frequency: 75 },
  { id: 'dx-08', category: 'diagnostico', code: 'N39.0', name: 'N39.0 - Infeccion del tracto urinario (ITU)', frequency: 92 },
  { id: 'dx-09', category: 'diagnostico', code: 'K29.7', name: 'K29.7 - Gastritis no especificada', frequency: 80 },
  { id: 'dx-10', category: 'diagnostico', code: 'K80.0', name: 'K80.0 - Colelitiasis con colecistitis aguda', frequency: 78 },
  { id: 'dx-11', category: 'diagnostico', code: 'A41.9', name: 'A41.9 - Sepsis / Choque septico no especificado', frequency: 70 },
  { id: 'dx-12', category: 'diagnostico', code: 'I21.9', name: 'I21.9 - Infarto agudo de miocardio sin elevacion del ST (IAMSEST)', frequency: 76 },
  { id: 'dx-13', category: 'diagnostico', code: 'I21.0', name: 'I21.0 - Infarto agudo de miocardio con elevacion del ST (IAMCEST)', frequency: 74 },
  { id: 'dx-14', category: 'diagnostico', code: 'I63.9', name: 'I63.9 - Accidente cerebrovascular isquémico agudo', frequency: 72 },
  { id: 'dx-15', category: 'diagnostico', code: 'K35.8', name: 'K35.8 - Apendicitis aguda confirmada', frequency: 68 },
  { id: 'dx-16', category: 'diagnostico', code: 'D64.9', name: 'D64.9 - Anemia normocitica normocromica a estudio', frequency: 79 },
  { id: 'dx-17', category: 'diagnostico', code: 'E86.0', name: 'E86.0 - Deshidratacion y deplecion hidroelectrolitica', frequency: 83 },
  { id: 'dx-18', category: 'diagnostico', code: 'J96.0', name: 'J96.0 - Insuficiencia respiratoria aguda tipo I', frequency: 77 },

  // Motivos de Consulta
  { id: 'mc-01', category: 'motivo_consulta', name: 'Dolor toracico opresivo irradiado a mandibula/brazo izquierdo', code: 'MC-001', frequency: 95 },
  { id: 'mc-02', category: 'motivo_consulta', name: 'Disnea progresiva de pequenos a medianos esfuerzos', code: 'MC-002', frequency: 93 },
  { id: 'mc-03', category: 'motivo_consulta', name: 'Dolor abdominal agudo y distension', code: 'MC-003', frequency: 91 },
  { id: 'mc-04', category: 'motivo_consulta', name: 'Sindrome febril agudo en estudio', code: 'MC-004', frequency: 89 },
  { id: 'mc-05', category: 'motivo_consulta', name: 'Deterioro del estado de conciencia y desorientacion', code: 'MC-005', frequency: 78 },
  { id: 'mc-06', category: 'motivo_consulta', name: 'Sincope y caida desde su propia altura', code: 'MC-006', frequency: 74 },
  { id: 'mc-07', category: 'motivo_consulta', name: 'Tos productiva con expectoracion mucopurulenta', code: 'MC-007', frequency: 82 },
  { id: 'mc-08', category: 'motivo_consulta', name: 'Edema bilateral de miembros inferiores', code: 'MC-008', frequency: 85 },
  { id: 'mc-09', category: 'motivo_consulta', name: 'Nauseas y emesis incoercible', code: 'MC-009', frequency: 80 },
  { id: 'mc-10', category: 'motivo_consulta', name: 'Cefalea holocraneana punzante refractaria', code: 'MC-010', frequency: 76 },
  { id: 'mc-11', category: 'motivo_consulta', name: 'Hemorragia de vias digestivas (Melena / Hematemesis)', code: 'MC-011', frequency: 72 },

  // Antecedentes Médicos
  { id: 'ant-01', category: 'antecedente', name: 'Hipertension arterial de larga evolucion', code: 'ANT-001', frequency: 98 },
  { id: 'ant-02', category: 'antecedente', name: 'Diabetes mellitus tipo 2 insulinorrequiriente', code: 'ANT-002', frequency: 94 },
  { id: 'ant-03', category: 'antecedente', name: 'Dislipidemia mixta', code: 'ANT-003', frequency: 89 },
  { id: 'ant-04', category: 'antecedente', name: 'Cardiopatia isquemica con revascularizacion percutanea', code: 'ANT-004', frequency: 80 },
  { id: 'ant-05', category: 'antecedente', name: 'Asma bronquial en tratamiento controlador', code: 'ANT-005', frequency: 79 },
  { id: 'ant-06', category: 'antecedente', name: 'Enfermedad renal cronica estadio 3b', code: 'ANT-006', frequency: 75 },
  { id: 'ant-07', category: 'antecedente', name: 'Hipotiroidismo primario sustituido', code: 'ANT-007', frequency: 84 },
  { id: 'ant-08', category: 'antecedente', name: 'Colecistectomia por laparoscopia', code: 'ANT-008', frequency: 77 },
  { id: 'ant-09', category: 'antecedente', name: 'Apendicectomia previa', code: 'ANT-009', frequency: 81 },
  { id: 'ant-10', category: 'antecedente', name: 'Fibrilacion auricular paroxistica anticoagulada', code: 'ANT-010', frequency: 71 },

  // Hallazgos de Examen Físico
  { id: 'hf-01', category: 'hallazgo_examen', name: 'Murmullo vesicular conservado, sin ruidos agregados', code: 'HF-001', frequency: 99 },
  { id: 'hf-02', category: 'hallazgo_examen', name: 'Roncus y sibilancias espiratorias difusas', code: 'HF-002', frequency: 82 },
  { id: 'hf-03', category: 'hallazgo_examen', name: 'Estertores crepitantes tele-espiratorios en bases pulmonares', code: 'HF-003', frequency: 84 },
  { id: 'hf-04', category: 'hallazgo_examen', name: 'Ruidos cardiacos ritmicos sin soplos ni frote pericardico', code: 'HF-004', frequency: 95 },
  { id: 'hf-05', category: 'hallazgo_examen', name: 'Soplo holosistolico grado II/VI en foco mitral', code: 'HF-005', frequency: 73 },
  { id: 'hf-06', category: 'hallazgo_examen', name: 'Ingurgitacion yugular grado II a 45 grados', code: 'HF-006', frequency: 70 },
  { id: 'hf-07', category: 'hallazgo_examen', name: 'Abdomen blando, depresible, no doloroso a la palpacion', code: 'HF-007', frequency: 96 },
  { id: 'hf-08', category: 'hallazgo_examen', name: 'Dolor a la palpacion profunda en hipocondrio derecho con signo de Murphy dudoso', code: 'HF-008', frequency: 68 },
  { id: 'hf-09', category: 'hallazgo_examen', name: 'Edema con fovea grado ++ en tercio distal de ambos miembros inferiores', code: 'HF-009', frequency: 85 },
  { id: 'hf-10', category: 'hallazgo_examen', name: 'Pupilas isocoricas, fotorreactivas a la luz directa y consensual', code: 'HF-010', frequency: 98 },
  { id: 'hf-11', category: 'hallazgo_examen', name: 'Alerta, lucido, orientado en tiempo, espacio y persona', code: 'HF-011', frequency: 99 },
  { id: 'hf-12', category: 'hallazgo_examen', name: 'Marcha y fuerza muscular 5/5 conservadas en las cuatro extremidades', code: 'HF-012', frequency: 92 }
];
